.\" Copyright (c) 2014 Stijn van Dongen
.TH "clm residue" 1 "16 May 2014" "clm residue 14-137" "USER COMMANDS "
.po 2m
.de ZI
.\" Zoem Indent/Itemize macro I.
.br
'in +\\$1
.nr xa 0
.nr xa -\\$1
.nr xb \\$1
.nr xb -\\w'\\$2'
\h'|\\n(xau'\\$2\h'\\n(xbu'\\
..
.de ZJ
.br
.\" Zoem Indent/Itemize macro II.
'in +\\$1
'in +\\$2
.nr xa 0
.nr xa -\\$2
.nr xa -\\w'\\$3'
.nr xb \\$2
\h'|\\n(xau'\\$3\h'\\n(xbu'\\
..
.if n .ll -2m
.am SH
.ie n .in 4m
.el .in 8m
..
.SH NAME
clm residue \- extend clustering of subgraph to clustering of graph\&.

clmresidue is not in actual fact a program\&. This manual
page documents the behaviour and options of the clm program when
invoked in mode \fIresidue\fP\&. The options \fB-h\fP, \fB--apropos\fP,
\fB--version\fP, \fB-set\fP, \fB--nop\fP are accessible
in all \fBclm\fP modes\&. They are described
in the \fBclm\fP manual page\&.
.SH SYNOPSIS

\fBclm residue\fP
\fB-icl\fP fname (\fIinput clustering\fP)
\fB-imx\fP fname (\fIinput graph\fP)
\fB[-rpm\fP fname (\fIresidue projection matrix\fP)\fB]\fP
\fB[-o\fP fname (\fIoutput clustering file\fP)\fB]\fP
.SH DESCRIPTION

The cluster file presumably contains a clustering of a subgraph of the
graph\ \&\fCG\fP contained by the matrix file, implying that the row domain of
that clustering is a subset of the node domain of the graph\&. \fBclm residue\fP will
compute a simple upwards projection of that clustering, resulting in a
clustering of\ \&\fCG\fP\&.
.SH OPTIONS

.ZI 2m "\fB-imx\fP fname (\fIinput graph\fP)"
\&
.br
.in -2m

.ZI 2m "\fB-icl\fP fname (\fIinput clustering\fP)"
\&
.br
.in -2m

.ZI 2m "\fB-rpm\fP fname (\fIresidue projection matrix\fP)"
\&
.br
The name for the file in which the residue projection matrix is stored\&.
It contains for each node and for each cluster in the input clustering
the combined weight of the (edges to the) neighbours of that node
in that cluster\&.
The default output file name is \fCout\&.rpm\fP\&.
.in -2m

.ZI 2m "\fB-o\fP fname (\fIoutput clustering file\fP)"
\&
.br
The name for the file in which the majority vote projection clustering
is stored\&. Aka the majority vote projection clustering storage file name\&.

This embodies a very crude approach to distributing the missing nodes in the
input clustering onto that same cluster\&. For each node, the cluster is
taken for which the residue projection is the largest (see above)\&. The
residue (i\&.e\&. the set of missing nodes) is initially viewed as a cluster;
the set of nodes for which the projection is largest for the residue itself
will form a new cluster, if it is not empty\&.

By default output is sent to STDOUT\&.
.in -2m
.SH AUTHOR

Stijn van Dongen\&.
.SH SEE ALSO

\fBmclfamily(7)\fP for an overview of all the documentation
and the utilities in the mcl family\&.
